joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: base_to_wheel_fl_link
  right_wheel: base_to_wheel_fr_link
  publish_rate: 50.0
  wheel_separation: 0.36 
  wheel_radius: 0.07     
  cmd_vel_timeout: 0.25
  base_frame_id: base_link
  enable_odom_tf: true

  pose_covariance_diagonal: [0.001, 0, 0, 0, 0, 0.03]
  twist_covariance_diagonal: [0.001, 0, 0, 0, 0, 0.03]

  odom_frame_id: odom
  odom_topic: odom
  cmd_vel_topic: cmd_vel
``
