joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: base_to_wheel_fl_link
  right_wheel: base_to_wheel_fr_link
  wheel_separation: 0.36
  wheel_diameter: 0.14
  cmd_vel_timeout: 0.25
  publish_rate: 50
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
