(cl:defpackage robot_bar-srv
  (:use )
  (:export
   "GETTABLEPOSITION"
   "<GETTABLEPOSITION-REQUEST>"
   "GETTABLEPOSITION-REQUEST"
   "<GETTABLEPOSITION-RESPONSE>"
   "GETTABLEPOSITION-RESPONSE"
  ))

