// Generated by gencpp from file robot_bar/GetTablePosition.msg
// DO NOT EDIT!


#ifndef ROBOT_BAR_MESSAGE_GETTABLEPOSITION_H
#define ROBOT_BAR_MESSAGE_GETTABLEPOSITION_H

#include <ros/service_traits.h>


#include <robot_bar/GetTablePositionRequest.h>
#include <robot_bar/GetTablePositionResponse.h>


namespace robot_bar
{

struct GetTablePosition
{

typedef GetTablePositionRequest Request;
typedef GetTablePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTablePosition
} // namespace robot_bar


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_bar::GetTablePosition > {
  static const char* value()
  {
    return "a5958a44ce6db6760f5e6109da65f88b";
  }

  static const char* value(const ::robot_bar::GetTablePosition&) { return value(); }
};

template<>
struct DataType< ::robot_bar::GetTablePosition > {
  static const char* value()
  {
    return "robot_bar/GetTablePosition";
  }

  static const char* value(const ::robot_bar::GetTablePosition&) { return value(); }
};


// service_traits::MD5Sum< ::robot_bar::GetTablePositionRequest> should match
// service_traits::MD5Sum< ::robot_bar::GetTablePosition >
template<>
struct MD5Sum< ::robot_bar::GetTablePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_bar::GetTablePosition >::value();
  }
  static const char* value(const ::robot_bar::GetTablePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_bar::GetTablePositionRequest> should match
// service_traits::DataType< ::robot_bar::GetTablePosition >
template<>
struct DataType< ::robot_bar::GetTablePositionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_bar::GetTablePosition >::value();
  }
  static const char* value(const ::robot_bar::GetTablePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_bar::GetTablePositionResponse> should match
// service_traits::MD5Sum< ::robot_bar::GetTablePosition >
template<>
struct MD5Sum< ::robot_bar::GetTablePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_bar::GetTablePosition >::value();
  }
  static const char* value(const ::robot_bar::GetTablePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_bar::GetTablePositionResponse> should match
// service_traits::DataType< ::robot_bar::GetTablePosition >
template<>
struct DataType< ::robot_bar::GetTablePositionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_bar::GetTablePosition >::value();
  }
  static const char* value(const ::robot_bar::GetTablePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_BAR_MESSAGE_GETTABLEPOSITION_H
