// Generated by gencpp from file robot_bar/Order.msg
// DO NOT EDIT!


#ifndef ROBOT_BAR_MESSAGE_ORDER_H
#define ROBOT_BAR_MESSAGE_ORDER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_bar
{
template <class ContainerAllocator>
struct Order_
{
  typedef Order_<ContainerAllocator> Type;

  Order_()
    : id_ordine()
    , prodotto()
    , tavolo(0)  {
    }
  Order_(const ContainerAllocator& _alloc)
    : id_ordine(_alloc)
    , prodotto(_alloc)
    , tavolo(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_ordine_type;
  _id_ordine_type id_ordine;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _prodotto_type;
  _prodotto_type prodotto;

   typedef int32_t _tavolo_type;
  _tavolo_type tavolo;





  typedef boost::shared_ptr< ::robot_bar::Order_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_bar::Order_<ContainerAllocator> const> ConstPtr;

}; // struct Order_

typedef ::robot_bar::Order_<std::allocator<void> > Order;

typedef boost::shared_ptr< ::robot_bar::Order > OrderPtr;
typedef boost::shared_ptr< ::robot_bar::Order const> OrderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_bar::Order_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_bar::Order_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_bar::Order_<ContainerAllocator1> & lhs, const ::robot_bar::Order_<ContainerAllocator2> & rhs)
{
  return lhs.id_ordine == rhs.id_ordine &&
    lhs.prodotto == rhs.prodotto &&
    lhs.tavolo == rhs.tavolo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_bar::Order_<ContainerAllocator1> & lhs, const ::robot_bar::Order_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_bar

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_bar::Order_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_bar::Order_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_bar::Order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_bar::Order_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_bar::Order_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_bar::Order_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_bar::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "423d4314acfad0d1e32fd5c417d3147d";
  }

  static const char* value(const ::robot_bar::Order_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x423d4314acfad0d1ULL;
  static const uint64_t static_value2 = 0xe32fd5c417d3147dULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_bar::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_bar/Order";
  }

  static const char* value(const ::robot_bar::Order_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_bar::Order_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id_ordine\n"
"string prodotto\n"
"int32 tavolo\n"
;
  }

  static const char* value(const ::robot_bar::Order_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_bar::Order_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id_ordine);
      stream.next(m.prodotto);
      stream.next(m.tavolo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Order_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_bar::Order_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_bar::Order_<ContainerAllocator>& v)
  {
    s << indent << "id_ordine: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id_ordine);
    s << indent << "prodotto: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.prodotto);
    s << indent << "tavolo: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tavolo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_BAR_MESSAGE_ORDER_H
